import z from 'zod'

const id = z.string()
const created = z.number().nonnegative()
const apiVersion = z.string().nullish()
const livemode = z.boolean()
const pending_webhooks = z.int().nonnegative()

export const StripeEvents = {
    'account.updated': z.any(),
    'account.application.deauthorized': z.any(),
    'account.external_account.created': z.any(),
    'account.external_account.deleted': z.any(),
    'account.external_account.updated': z.any(),
    'application_fee.created': z.any(),
    'application_fee.refunded': z.any(),
    'application_fee.refund.updated': z.any(),
    'balance.available': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('balance.available'),
        data: z.object({
            object: z.object({
                available: z.array(
                    z.object({
                        amount: z.number(),
                        currency: z.string(),
                    }),
                ),
                livemode: z.boolean(),
                object: z.literal('balance'),
                pending: z.array(
                    z.object({
                        amount: z.number(),
                        currency: z.string(),
                    }),
                ),
            }),
        }),
    }),
    'billing_portal.configuration.created': z.any(),
    'billing_portal.configuration.updated': z.any(),
    'billing_portal.session.created': z.any(),
    'capability.updated': z.any(),
    'charge.captured': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('charge.captured'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'charge.dispute.closed': z.any(),
    'charge.dispute.created': z.any(),
    'charge.dispute.funds_reinstated': z.any(),
    'charge.dispute.funds_withdrawn': z.any(),
    'charge.dispute.updated': z.any(),
    'charge.expired': z.any(),
    'charge.failed': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('charge.failed'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'charge.pending': z.any(),
    'charge.refunded': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('charge.refunded'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'charge.succeeded': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('charge.succeeded'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'charge.updated': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('charge.updated'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'checkout.session.async_payment_failed': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('checkout.session.async_payment_failed'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'checkout.session.async_payment_succeeded': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('checkout.session.async_payment_succeeded'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'checkout.session.completed': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('checkout.session.completed'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'checkout.session.expired': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('checkout.session.expired'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'coupon.created': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('coupon.created'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'coupon.deleted': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('coupon.deleted'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'coupon.updated': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('coupon.updated'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'credit_note.created': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('credit_note.created'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'credit_note.updated': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('credit_note.updated'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'credit_note.voided': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('credit_note.voided'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'customer.created': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('customer.created'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'customer.deleted': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('customer.deleted'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'customer.updated': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('customer.updated'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'customer.discount.created': z.any(),
    'customer.discount.deleted': z.any(),
    'customer.discount.updated': z.any(),
    'customer.source.created': z.any(),
    'customer.source.deleted': z.any(),
    'customer.source.expiring': z.any(),
    'customer.source.updated': z.any(),
    'customer.subscription.created': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('customer.subscription.created'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'customer.subscription.deleted': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('customer.subscription.deleted'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'customer.subscription.paused': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('customer.subscription.paused'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'customer.subscription.pending_update_applied': z.any(),
    'customer.subscription.pending_update_expired': z.any(),
    'customer.subscription.resumed': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('customer.subscription.resumed'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'customer.subscription.trial_will_end': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('customer.subscription.trial_will_end'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'customer.subscription.updated': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('customer.subscription.updated'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'customer.tax_id.created': z.any(),
    'customer.tax_id.deleted': z.any(),
    'customer.tax_id.updated': z.any(),
    'customer_cash_balance_transaction.created': z.any(),
    'file.created': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('file.created'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'financial_connections.account.created': z.any(),
    'financial_connections.account.deactivated': z.any(),
    'financial_connections.account.disconnected': z.any(),
    'financial_connections.account.reactivated': z.any(),
    'financial_connections.account.refreshed_balance': z.any(),
    'identity.verification_session.canceled': z.any(),
    'identity.verification_session.created': z.any(),
    'identity.verification_session.processing': z.any(),
    'identity.verification_session.requires_input': z.any(),
    'identity.verification_session.verified': z.any(),
    'invoice.created': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('invoice.created'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'invoice.deleted': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('invoice.deleted'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'invoice.finalization_failed': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('invoice.finalization_failed'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'invoice.finalized': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('invoice.finalized'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'invoice.marked_uncollectible': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('invoice.marked_uncollectible'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'invoice.paid': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('invoice.paid'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'invoice.payment_action_required': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('invoice.payment_action_required'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'invoice.payment_failed': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('invoice.payment_failed'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'invoice.payment_succeeded': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('invoice.payment_succeeded'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'invoice.sent': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('invoice.sent'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'invoice.upcoming': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('invoice.upcoming'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'invoice.voided': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('invoice.voided'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'invoiceitem.created': z.any(),
    'invoiceitem.deleted': z.any(),
    'invoiceitem.updated': z.any(),
    'issuing_authorization.created': z.any(),
    'issuing_authorization.request': z.any(),
    'issuing_authorization.updated': z.any(),
    'issuing_card.created': z.any(),
    'issuing_card.updated': z.any(),
    'issuing_cardholder.created': z.any(),
    'issuing_cardholder.updated': z.any(),
    'issuing_dispute.closed': z.any(),
    'issuing_dispute.created': z.any(),
    'issuing_dispute.funds_reinstated': z.any(),
    'issuing_dispute.submitted': z.any(),
    'issuing_dispute.updated': z.any(),
    'issuing_settlement.created': z.any(),
    'issuing_settlement.updated': z.any(),
    'issuing_transaction.created': z.any(),
    'issuing_transaction.updated': z.any(),
    'mandate.updated': z.any(),
    'order.created': z.any(),
    'order.payment_failed': z.any(),
    'order.payment_succeeded': z.any(),
    'order.updated': z.any(),
    'order_return.created': z.any(),
    'payment_intent.amount_capturable_updated': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('payment_intent.amount_capturable_updated'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'payment_intent.canceled': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('payment_intent.canceled'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'payment_intent.created': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('payment_intent.created'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'payment_intent.payment_failed': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('payment_intent.payment_failed'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'payment_intent.processing': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('payment_intent.processing'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'payment_intent.requires_action': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('payment_intent.requires_action'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'payment_intent.succeeded': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('payment_intent.succeeded'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'payment_link.created': z.any(),
    'payment_link.updated': z.any(),
    'payment_method.attached': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('payment_method.attached'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'payment_method.automatically_updated': z.any(),
    'payment_method.detached': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('payment_method.detached'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'payment_method.updated': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('payment_method.updated'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'payout.canceled': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('payout.canceled'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'payout.created': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('payout.created'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'payout.failed': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('payout.failed'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'payout.paid': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('payout.paid'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'payout.reconciliation_completed': z.any(),
    'payout.updated': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('payout.updated'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'person.created': z.any(),
    'person.deleted': z.any(),
    'person.updated': z.any(),
    'plan.created': z.any(),
    'plan.deleted': z.any(),
    'plan.updated': z.any(),
    'price.created': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('price.created'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'price.deleted': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('price.deleted'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'price.updated': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('price.updated'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'product.created': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('product.created'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'product.deleted': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('product.deleted'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'product.updated': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('product.updated'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'promotion_code.created': z.any(),
    'promotion_code.updated': z.any(),
    'quote.accepted': z.any(),
    'quote.canceled': z.any(),
    'quote.created': z.any(),
    'quote.finalized': z.any(),
    'quote.phase_ended': z.any(),
    'quote.phase_started': z.any(),
    'quote.expired': z.any(),
    'quote.updated': z.any(),
    'radar.early_fraud_warning.created': z.any(),
    'radar.early_fraud_warning.updated': z.any(),
    'refund.created': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('refund.created'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'refund.updated': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('refund.updated'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'reporting.report_run.failed': z.any(),
    'reporting.report_run.succeeded': z.any(),
    'review.closed': z.any(),
    'review.opened': z.any(),
    'setup_intent.canceled': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('setup_intent.canceled'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'setup_intent.created': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('setup_intent.created'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'setup_intent.requires_action': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('setup_intent.requires_action'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'setup_intent.setup_failed': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('setup_intent.setup_failed'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'setup_intent.succeeded': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('setup_intent.succeeded'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'sigma.scheduled_query_run.created': z.any(),
    'sku.created': z.any(),
    'sku.deleted': z.any(),
    'sku.updated': z.any(),
    'source.canceled': z.any(),
    'source.chargeable': z.any(),
    'source.failed': z.any(),
    'source.mandate_notification': z.any(),
    'source.refund_attributes_required': z.any(),
    'source.transaction.created': z.any(),
    'source.transaction.updated': z.any(),
    'subscription_schedule.aborted': z.any(),
    'subscription_schedule.canceled': z.any(),
    'subscription_schedule.completed': z.any(),
    'subscription_schedule.created': z.any(),
    'subscription_schedule.expiring': z.any(),
    'subscription_schedule.released': z.any(),
    'subscription_schedule.updated': z.any(),
    'tax.calculation.created': z.any(),
    'tax.settings.updated': z.any(),
    'terminal.reader.action_succeeded': z.any(),
    'terminal.reader.action_failed': z.any(),
    'terminal.connection_token.created': z.any(),
    'test_helpers.test_clock.advancing': z.any(),
    'test_helpers.test_clock.created': z.any(),
    'test_helpers.test_clock.deleted': z.any(),
    'test_helpers.test_clock.idle': z.any(),
    'topup.created': z.any(),
    'topup.failed': z.any(),
    'topup.reversed': z.any(),
    'topup.succeeded': z.any(),
    'transfer.created': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('transfer.created'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'transfer.reversed': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('transfer.reversed'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'transfer.updated': z.object({
        id,
        object: z.literal('event'),
        api_version: apiVersion,
        created,
        livemode,
        pending_webhooks,
        type: z.literal('transfer.updated'),
        data: z.object({
            object: z.any(),
        }),
    }),
    'treasury.credit_reversal.created': z.any(),
    'treasury.credit_reversal.posted': z.any(),
    'treasury.debit_reversal.completed': z.any(),
    'treasury.debit_reversal.created': z.any(),
    'treasury.debit_reversal.initial_credit_granted': z.any(),
    'treasury.financial_account.created': z.any(),
    'treasury.financial_account.closed': z.any(),
    'treasury.financial_account.features_status_updated': z.any(),
    'treasury.inbound_transfer.canceled': z.any(),
    'treasury.inbound_transfer.created': z.any(),
    'treasury.inbound_transfer.failed': z.any(),
    'treasury.inbound_transfer.succeeded': z.any(),
    'treasury.outbound_account_credit_reversed': z.any(),
    'treasury.outbound_account_credits.canceled': z.any(),
    'treasury.outbound_account_credits.created': z.any(),
    'treasury.outbound_account_credits.failed': z.any(),
    'treasury.outbound_account_debit_reversed': z.any(),
    'treasury.outbound_account_debits.canceled': z.any(),
    'treasury.outbound_account_debits.created': z.any(),
    'treasury.outbound_account_debits.failed': z.any(),
    'treasury.outbound_payment.canceled': z.any(),
    'treasury.outbound_payment.created': z.any(),
    'treasury.outbound_payment.expected_arrival_date_updated': z.any(),
    'treasury.outbound_payment.failed': z.any(),
    'treasury.outbound_payment.posted': z.any(),
    'treasury.outbound_payment.returned': z.any(),
} as const

export type StripeEvent = keyof typeof StripeEvents
