on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PNPM Setup
        uses: pnpm/action-setup@v4

      - name: Node Setup
        uses: actions/setup-node@v4
        with: 
          node-version: 25
          cache: pnpm 

      - name: Doppler Setup
        uses: dopplerhq/cli-action@v3

      - name: Install Deps
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Format
        run: pnpm run format:check

      - name: Check Types
        run: pnpm run check-types

      - name: Lint
        run: pnpm run lint 

      - name: Test
        run: doppler run -- pnpm run test
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
